GeoDocs/GeoDocs/carto/urls.py
from django.conf.urls import url, include
from . import views

app_name='carto'
urlpatterns = [
    url(r'^$', views.mapa, name="Mapa"),
    url(r'^Test$', views.mapaPato, name="MapaPato"),
    url(r'^Data/(?P<idMapa>\d+)/$', views.loadPoligonos, name="Data"),
    url(r'^DataAll/(?P<idMapa>\d+)/$', views.loadAll, name="DataAll"),
    url(r'^Puntos/(?P<idMapa>\d+)/$', views.loadPuntos, name="Puntos"),
    url(r'^Lineas/(?P<idMapa>\d+)/$', views.loadLineas, name="Lineas"),
    url(r'^Poligonos/(?P<idMapa>\d+)/$', views.loadPoligonos, name="Poligonos"),
    url(r'^nuevoMapa$', views.crearNuevoMapa, name="nuevoMapa"),
    url(r'^eliminarMapa$', views.eliminarMapa, name="eliminarMapa"),
    url(r'^updateNP$', views.actualizarNombreMapa, name="updateNP"),
    url(r'^updateNG$', views.actualizarNombreGeometria, name="updateNG"),
    url(r'^actualizar$', views.actualizar, name="actualizar"),
    url(r'^insertar$', views.insertar, name="insertar"),
    url(r'^eliminar$', views.eliminar, name="eliminar")
]

GeoDocs/GeoDocs/foro/urls.py
from django.conf.urls import url, include
from .views import *
from . import views
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.views import logout
import notifications.urls


app_name='foro'

from django.conf.urls import (
handler400, handler403, handler404, handler500
)


urlpatterns = [
    url(r'^$', ViewUsuario.as_view(), name="ingresar"),
    url(r'^foro/administrador/visualizaruser$', login_required(ViewVisualizarUser.as_view()), name="visualizaruser"),
    url(r'^foro/perfil/visualozarperfiles/$', login_required(ViewVisualizarPerfiles.as_view()), name="visualizarperfils"),
    url(r'^foro/administrador/visualizaradministrador$', login_required(ViewVisualizarAdministradores.as_view()), name="visualizaradministrador"),
    url(r'^foro/administrador/visualizaradministrador/$', login_required(ViewBuscarAdministradores.as_view()), name="buscaradministradores"),
    url(r'^foro/administrador/visualizaruser/$', login_required(ViewBuscarUser.as_view()), name="busquedauserr"),
    url(r'^foro/administrador/visualizaruser/eliminaruser/(?P<username>[\w.@+-]+)/$', login_required(ViewEliminarUser.as_view()), name="eliminaruser"),
    url(r'^foro/administrador/$', login_required(ViewVistaAdministrador.as_view()), name="administradorr"),
    url(r'^foro/administrador/registrodeperfiles/$', login_required(ViewRegistroPerfilesUser.as_view()), name="registrodeperfile"),

    url(r'^Bienvenido/$', login_required(ViewForoBienvenido.as_view()), name="Bienvenido"),

    url(r'^Temas_Discusion/(?P<pk>\d+)/$', login_required(ViewVerListaPost.as_view()), name="mostrarListadoPost"),

    url(r'^perfil/', login_required(ViewVerPerfil.as_view()), name="perfil"),

    url(r'^registrotopico/', login_required(ViewRegistroTopico.as_view()), name="registro"),
    url(r'^Editar/', login_required(ViewListarTopicos.as_view()), name="Editar"),

    url(r'^ingresartemas/(?P<pk>\d+)$', login_required(ViewRegistroTemaEnPost.as_view()), name="ingresartemas"),

    url(r'^actualizarCategoria/$', login_required(ViewEditarCategoriaTopico.as_view()), name="actualizarCategoria"),
    url(r'^eliminarCategoria/$', login_required(ViewEliminarCategoriaTopico.as_view()), name="eliminarCategoria"),
    url(r'^agregarcategoria/$', login_required(ViewRegistroCategoriaTopico.as_view()), name="agregarcategoria"),

    url(r'^post/(?P<pk>\d+)$', login_required(ViewTemasDiscusion.as_view()), name="temadiscusion"),
    url(r'^editarcomentario/(?P<pk>\d+)$', login_required(ViewModificaComentario.as_view()), name="editarcomentario"),
    url(r'^eliminarcomentario/(?P<comentario>\d+)$', login_required(ViewEliminarComentario.as_view()), name="eliminarcomentario"),

    url(r'^actualizar/$', login_required(ViewEditarTopico.as_view()), name="actualizar"),
    url(r'^eliminar/$', login_required(ViewEliminarTopico.as_view()), name="eliminar"),

    url(r'^eliminar_post/(?P<post>\d+)$', login_required(ViewEliminarPost.as_view()), name="eliminarpost"),
    url(r'^Temas_Discusion/comentario/editarpost/(?P<post>\d+)$', login_required(ViewModificaPost.as_view()), name="editarpost"),

    url(r'^registrolike/', login_required(ViewRegistrarLike.as_view()), name="registrolike"),
    url(r'^eliminarlike/', login_required(ViewEliminarLike.as_view()), name="eliminarlike"),

    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),









    url(r'^foro/createuser/registrouser/$', login_required(ViewRegistroUser.as_view()), name="registrouser"),


    url(r'^foro/administrador/editarperfiles/(?P<pk>\d+)/$', login_required(ViewModificarPerfilesUser.as_view()), name="editarperfiles"),

    url(r'^foro/perfil/modificaruser/(?P<pk>\d+)/$', login_required(ViewModificarMiUser.as_view()), name="modificardatosuser"),
    url(r'^foro/perfil/modificardatosuser/(?P<username>[\w.@+-]+)/$', login_required(ViewModificarUser.as_view()), name="modificadouser"),

    url(r'^foro/perfil/eliminarperfile/(?P<pk>\d+)/$', login_required(ViewEliminarPerfilUser.as_view()), name="eliminarperfiles"),

    url(r'^', include('notifications.urls', namespace='notifications')),
    url(r'^foro/bienvenido/notificacionesredirrecionamiento/(?P<id>\d+)/(?P<informacion>[\w ]+)/(?P<pk>\d+)//$', login_required(ViewRedireccionNotificacions.as_view()), name="Notificacionesredirrecionamiento"),
    url(r'^foro/Bienvenido/Visualizarnotificaciones/$', ViewVisualizarNotificaciones.as_view(), name="visualizarnotificaciones"),




]

GeoDocs/GeoDocs/main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.views import logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth import views as v
from django.conf.urls import handler404,handler500

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'foro/', include('foro.urls')),
    path(r'repositorio/', include('repositorio.urls')),
    path(r'conversor/', include('conversor.urls')),
    path(r'mapa/', include('carto.urls')),
    url(r'^reset/password_reset', password_reset, {'template_name':'registration/password_reset_form.html','email_template_name': 'registration/password_reset_email.html'},name='password_reset'),
    url(r'^password_reset_done', password_reset_done,{'template_name': 'registration/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,{'template_name': 'registration/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},name='password_reset_complete'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
handler404 = 'foro.views.error_404_view'
handler500 = 'foro.views.error_500'

GeoDocs/GeoDocs/carto/models.py
from django.contrib.gis.db import models
from cuentas.models import User

class WorldBorder(models.Model):
    nombre = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=4326)
    def __str__(self):
        return self.name

class Mapa(models.Model):
    nombre = models.CharField(max_length=50)
    dueño = models.ForeignKey(User,  on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class Poligono(models.Model):
    nombre = models.CharField(max_length=50)
    geometry = models.PolygonField(srid=4326)
    mapa = models.ForeignKey(Mapa,  on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class Punto(models.Model):
    nombre = models.CharField(max_length=50)
    geometry = models.PointField(srid=4326)
    mapa = models.ForeignKey(Mapa,  on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class CadenaLinea(models.Model):
    nombre = models.CharField(max_length=50)
    geometry = models.LineStringField(srid=4326)
    mapa = models.ForeignKey(Mapa,  on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

GeoDocs/GeoDocs/carto/forms.py
from django.contrib.gis import forms
from django.views.generic import UpdateView
from leaflet.forms.widgets import LeafletWidget

from .models import WorldBorder


class WorldBorderForm(forms.Form):
    class Meta:
        name = WorldBorder
        fields = ('name', 'geom')
        widgets = {'geom': LeafletWidget()}

class EditWorldBorder(UpdateView):
    model = WorldBorder
    form_class = WorldBorderForm
    template_name = 'carto/mapa.html'

class MyGeoForm(forms.Form):
    point = forms.MultiPolygonField(widget=forms.OSMWidget(attrs={'map_width': 800, 'map_height': 500}))

GeoDocs/GeoDocs/carto/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.serializers import serialize
from .models import Mapa, Poligono, Punto, CadenaLinea
from cuentas.models import User
from carto.forms import *
from django.views.decorators.csrf import ensure_csrf_cookie
from django.contrib.gis.geos import GEOSGeometry

@ensure_csrf_cookie
def mapa(request):
    usuario = request.user
    usuario = User.objects.get(email=usuario)
    queryset = Mapa.objects.filter(dueño=usuario)
    return render(request, 'carto/testingPato.html', {'mapas':queryset})

def mapaPato(request):
    return render(request, 'carto/testingPato.html')

@ensure_csrf_cookie
def loadMaps(request):
    usuario = request.POST.get('usuario')
    layers = serialize('geojson', Mapa.objects.get())
    return HttpResponse(layers, content_type='json')

def loadPoligonos(request, idMapa):
    poligonos = serialize('geojson', Poligono.objects.filter(mapa=idMapa))
    return HttpResponse(poligonos, content_type='json')

def loadPuntos(request, idMapa):
    puntos = serialize('geojson', Punto.objects.filter(mapa=idMapa))
    return HttpResponse(puntos, content_type='json')

def loadLineas(request, idMapa):
    lineas = serialize('geojson', CadenaLinea.objects.filter(mapa=idMapa))
    return HttpResponse(lineas, content_type='json')

def loadAll(request, idMapa):
    todos = list()
    poligonos = Poligono.objects.filter(mapa=idMapa)
    puntos = Punto.objects.filter(mapa=idMapa)
    lineas = CadenaLinea.objects.filter(mapa=idMapa)
    for x in puntos:
        todos.append(x)
    for x in poligonos:
        todos.append(x)
    for x in lineas:
        todos.append(x)
    test = serialize('geojson', todos)
    return HttpResponse(test, content_type='json')

def crearNuevoMapa(request):
    nombre = request.POST.get("nombre")
    usuario = User.objects.get(email=request.user)
    try:
        mapa = Mapa(nombre=nombre, dueño=usuario)
        mapa.save()
    except Mapa.DoesNotExist:
        mapa = null
    return HttpResponse(mapa.pk)

def eliminarMapa(request):
    idMapa = request.POST.get("idMapa")
    res = "null"
    try:
        mapa = Mapa.objects.get(pk=idMapa)
        mapa.delete();
        res = "Se elimino el mapa con exito"
    except Mapa.DoesNotExist:
        res = "No se pudo concretar la eliminación"
    return HttpResponse(res)

def actualizarNombreMapa(request):
    idMapa = request.POST.get("idMapa")
    nuevoNombre = request.POST.get("nuevoNombre")
    try:
        mapa = Mapa.objects.get(pk=idMapa)
        mapa.nombre = nuevoNombre
        mapa.save()
    except Mapa.DoesNotExist:
        mapa = null
    return HttpResponse(mapa)

def actualizar(request):
    temp = json.loads(request.POST.get('datos'))
    for layer in temp:
        type = layer['type']
        if(type == 'Point'):
            punto = Punto.objects.get(pk=layer['id'])
            punto.geometry = GEOSGeometry(json.dumps(layer['geom']))
            punto.save()
        if(type == 'Polygon'):
            poligono = Poligono.objects.get(pk=layer['id'])
            poligono.geometry = GEOSGeometry(json.dumps(layer['geom']))
            poligono.save()
        if(type == 'LineString'):
            cadenaLinea = CadenaLinea.objects.get(pk=layer['id'])
            cadenaLinea.geometry = GEOSGeometry(json.dumps(layer['geom']))
            print(json.dumps(layer['geom']))
            cadenaLinea.save()
    return HttpResponse("Modificación realizada")

def actualizarNombreGeometria(request):
    idGeometria = request.POST.get('idGeometria')
    type = request.POST.get('tipo')
    nuevoNombre = request.POST.get('nombre')
    if(type == 'Point'):
        punto = Punto.objects.get(pk=idGeometria)
        punto.nombre = nuevoNombre
        punto.save()
    if(type == 'Polygon'):
        poligono = Poligono.objects.get(pk=idGeometria)
        poligono.nombre = nuevoNombre
        poligono.save()
    if(type == 'LineString'):
        cadenaLinea = CadenaLinea.objects.get(pk=idGeometria)
        cadenaLinea.nombre = nuevoNombre
        cadenaLinea.save()
    return HttpResponse("Modificación realizada")

def insertar(request):
    nombre = request.POST.get('nombre')
    coords = request.POST.get('coordenadas')
    type = request.POST.get('tipo')
    idMapa = request.POST.get('idMapa')
    mapa = Mapa.objects.get(pk=idMapa)
    if(type == "Polygon"):
        poligono = Poligono(nombre=nombre, geometry=GEOSGeometry(coords), mapa=mapa)
        poligono.save()
    if(type == "Point"):
        punto = Punto(nombre=nombre, geometry=GEOSGeometry(coords), mapa=mapa)
        punto.save()
    if(type == 'LineString'):
        cadenaLinea = CadenaLinea(nombre=nombre, geometry=GEOSGeometry(coords), mapa=mapa)
        cadenaLinea.save()
    return HttpResponse("Se registro la figura con exito")

def eliminar(request):
    idLayer = request.POST.get('idLayer')
    type = request.POST.get('tipo')
    if(type == "Polygon"):
        Poligono.objects.filter(pk=idLayer).delete()
    if(type == "Point"):
        Punto.objects.filter(pk=idLayer).delete()
    if(type == 'LineString'):
        CadenaLinea.objects.filter(pk=idLayer).delete()
    return HttpResponse("Se elimino con exito")

GeoDocs/GeoDocs/carto/templates/carto/respaldo.html
{% load leaflet_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  {% leaflet_js plugins="ALL" %}
  {% leaflet_css plugins="ALL" %}
  {{ form.media }}
	<title>Testing</title>

	<script src="{% static 'js/leaflet-src.js' %}"></script>
	<link rel="stylesheet" href="{% static 'css/leaflet.css' %}" />

	<script src="{% static 'leaflet/src/Leaflet.draw.js' %}"></script>
	<script src="{% static 'leaflet/src/Leaflet.Draw.Event.js' %}"></script>
	<link rel="stylesheet" href="{% static 'leaflet/dist/leaflet.draw.css' %}" />

	<script src="{% static 'leaflet/src/Toolbar.js' %}"></script>
	<script src="{% static 'leaflet/src/Tooltip.js' %}"></script>

	<script src="{% static 'leaflet/src/ext/GeometryUtil.js' %}"></script>
	<script src="{% static 'leaflet/src/ext/LatLngUtil.js' %}"></script>
	<script src="{% static 'leaflet/src/ext/LineUtil.Intersect.js' %}"></script>
	<script src="{% static 'leaflet/src/ext/Polygon.Intersect.js' %}"></script>
	<script src="{% static 'leaflet/src/ext/Polyline.Intersect.js' %}"></script>
	<script src="{% static 'leaflet/src/ext/TouchEvents.js' %}"></script>

	<script src="{% static 'leaflet/src/draw/DrawToolbar.js' %}"></script>
	<script src="{% static 'leaflet/src/draw/handler/Draw.Feature.js' %}"></script>
	<script src="{% static 'leaflet/src/draw/handler/Draw.SimpleShape.js' %}"></script>
	<script src="{% static 'leaflet/src/draw/handler/Draw.Polyline.js' %}"></script>
	<script src="{% static 'leaflet/src/draw/handler/Draw.Circle.js' %}"></script>
	<script src="{% static 'leaflet/src/draw/handler/Draw.Marker.js' %}"></script>
	<script src="{% static 'leaflet/src/draw/handler/Draw.Polygon.js' %}"></script>
	<script src="{% static 'leaflet/src/draw/handler/Draw.Rectangle.js' %}"></script>


	<script src="{% static 'leaflet/src/edit/EditToolbar.js' %}"></script>
	<script src="{% static 'leaflet/src/edit/handler/EditToolbar.Edit.js' %}"></script>
	<script src="{% static 'leaflet/src/edit/handler/EditToolbar.Delete.js' %}"></script>

	<script src="{% static 'leaflet/src/Control.Draw.js' %}"></script>

	<script src="{% static 'leaflet/src/edit/handler/Edit.Poly.js' %}"></script>
	<script src="{% static 'leaflet/src/edit/handler/Edit.SimpleShape.js' %}"></script>
	<script src="{% static 'leaflet/src/edit/handler/Edit.Circle.js' %}"></script>
	<script src="{% static 'leaflet/src/edit/handler/Edit.Rectangle.js' %}"></script>
	<script src="{% static 'leaflet/src/edit/handler/Edit.Marker.js' %}"></script>
</head>
<body>
	<div id="map" style="width: 800px; height: 600px; border: 1px solid #ccc"></div>

	<script>
		var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
			osmAttrib = '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors',
			osm = L.tileLayer(osmUrl, {maxZoom: 18, attribution: osmAttrib});
			map = new L.Map('map', {center: new L.LatLng(51.505, -0.04), zoom: 13}),
			drawnItems = L.featureGroup().addTo(map);
		L.control.layers({
		 'osm':osm.addTo(map),
		 "google": L.tileLayer('http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}', {
		 attribution: 'google'
		})
		}, {'drawlayer':drawnItems}, { position: 'topleft', collapsed: false }).addTo(map);

    var MapControlDraw = new L.Control.Draw({
			edit: {
				featureGroup: drawnItems,
				poly : {
					allowIntersection : false
				}
			},
			draw: {
				polygon : {
					allowIntersection: false,
					showArea:true
				}
			}
		})
    map.addControl(MapControlDraw);

		map.on(L.Draw.Event.CREATED, function(event) {
			var layer = event.layer;
			drawnItems.addLayer(layer);
		});

	</script>
</body>
</html>

GeoDocs/GeoDocs/carto/templates/carto/roba3.html
{% load leaflet_tags %}
{% load staticfiles %}
<html>
<head>
  {% leaflet_js %}
  <meta charset=utf-8 />
  <title>Carto</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <!-- Load Leaflet (not latest version due to dependencies) -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
    <script src="{% static 'js/leaflet.js' %}"></script>
    <script src="{% static 'js/leaflet.ajax.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.2/leaflet.draw.js"></script>

    <!-- Load Esri Leaflet from CDN -->
    <script src="https://unpkg.com/esri-leaflet@2.2.3/dist/esri-leaflet.js"
    integrity="sha512-YZ6b5bXRVwipfqul5krehD9qlbJzc6KOGXYsDjU9HHXW2gK57xmWl2gU6nAegiErAqFXhygKIsWPKbjLPXVb2g=="
    crossorigin=""></script>
    <!-- Leaflet Draw -->

    <link rel="stylesheet" href="https://unpkg.com/leaflet-draw@0.4.7/dist/leaflet.draw-src.css">


  <style>
    body { margin:0; padding:0; }
    #map { position: absolute; top:0; bottom:0; right:0; left:0; }
  </style>
</head>
<body>

<style>
  #info-pane {
    position: absolute;
    top: 10px;
    right: 10px;
    z-index: 400;
    padding: 1em;
    background: white;
    text-align: right;
  }
  #form {
    display: none;
  }
</style>

<div id='map'></div>
<script>
  function cargaLayers(map, options){
    var datasets = new L.GeoJSON.AJAX("{% url 'carto:Data' %}", {
      onEachFeature: function(feature, layer){
        layer.bindPopup(feature.properties.name.toString());
        editableLayers.addLayer(layer);
      }
    });
    datasets.addTo(map);
  }

  // Create the map
  var map = L.map('map').setView([-33.8650, -60.2094], 3);
  // Set up the OSM layer
  L.tileLayer(
    'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: 'Data © <a href="http://osm.org/copyright">OpenStreetMap</a>',
      maxZoom: 18
    }).addTo(map);
  // Initialise the FeatureGroup to store editable layers
  var editableLayers = new L.FeatureGroup();
  map.addLayer(editableLayers);
  var drawPluginOptions = {
    position: 'topleft',
    draw: {
      polygon: {
        allowIntersection: true, // Restricts shapes to simple polygons
        drawError: {
          color: '#e1e100', // Color the shape will turn when intersects
          message: '<strong>Oh snap!<strong> you can\'t draw that!' // Message that will show when intersect
        },
        shapeOptions: {
          color: '#97009c'
        }
      },
      // disable toolbar item by setting it to false
      polyline: false,
      circle: false, // Turns off this drawing tool
      rectangle: false,
      marker: false,
      },
    edit: {
      featureGroup: editableLayers, //REQUIRED!!
      edit: true,
      remove: true
    }
  };
  // Initialise the draw control and pass it the FeatureGroup of editable layers
  var drawControl = new L.Control.Draw(drawPluginOptions);
  map.addControl(drawControl);
  map.on('draw:created', function(e) {
    var type = e.layerType,
      layer = e.layer;
    if (type === 'marker') {
      layer.bindPopup('A popup!');
    }
    editableLayers.addLayer(layer);
  });
  map.on('draw:deleted', function(e) {
  });
  cargaLayers(map);
</script>

</body>
</html>