GeoDocs/GeoDocs/carto/urls.py
from django.conf.urls import url, include
from . import views

app_name='carto'
urlpatterns = [
    url(r'^$', views.mapa, name="Mapa"),
    url(r'^Test$', views.mapaPato, name="MapaPato"),
    url(r'^Data/(?P<idMapa>\d+)/$', views.loadPoligonos, name="Data"),
    url(r'^DataAll/(?P<idMapa>\d+)/$', views.loadAll, name="DataAll"),
    url(r'^Puntos/(?P<idMapa>\d+)/$', views.loadPuntos, name="Puntos"),
    url(r'^Lineas/(?P<idMapa>\d+)/$', views.loadLineas, name="Lineas"),
    url(r'^Poligonos/(?P<idMapa>\d+)/$', views.loadPoligonos, name="Poligonos"),
    url(r'^nuevoMapa$', views.crearNuevoMapa, name="nuevoMapa"),
    url(r'^eliminarMapa$', views.eliminarMapa, name="eliminarMapa"),
    url(r'^updateNP$', views.actualizarNombreMapa, name="updateNP"),
    url(r'^updateNG$', views.actualizarNombreGeometria, name="updateNG"),
    url(r'^actualizar$', views.actualizar, name="actualizar"),
    url(r'^insertar$', views.insertar, name="insertar"),
    url(r'^eliminar$', views.eliminar, name="eliminar")
]

GeoDocs/GeoDocs/conversor/urls.py
from django.conf.urls import url
from . import views
from .views import *
from django.contrib.auth.decorators import login_required

app_name='conversor'
urlpatterns = [
    url(r'^$', views.loadFormularioConversor, name="Conversor"),
    url(r'^exportar$', views.importarGeometria, name="exportar"),
    url(r'^update$', views.actualizar, name="update"),
    url(r'^calcular$', views.calcular, name="calcular"),

]

GeoDocs/GeoDocs/foro/urls.py
from django.conf.urls import url, include
from .views import *
from . import views
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth.views import logout
import notifications.urls


app_name='foro'

from django.conf.urls import (
handler400, handler403, handler404, handler500
)


urlpatterns = [
    url(r'^$', ViewUsuario.as_view(), name="ingresar"),
    url(r'^foro/administrador/visualizaruser$', login_required(ViewVisualizarUser.as_view()), name="visualizaruser"),
    url(r'^foro/perfil/visualozarperfiles/$', login_required(ViewVisualizarPerfiles.as_view()), name="visualizarperfils"),
    url(r'^foro/administrador/visualizaradministrador$', login_required(ViewVisualizarAdministradores.as_view()), name="visualizaradministrador"),
    url(r'^foro/administrador/visualizaradministrador/$', login_required(ViewBuscarAdministradores.as_view()), name="buscaradministradores"),
    url(r'^foro/administrador/visualizaruser/$', login_required(ViewBuscarUser.as_view()), name="busquedauserr"),
    url(r'^foro/administrador/visualizaruser/eliminaruser/(?P<username>[\w.@+-]+)/$', login_required(ViewEliminarUser.as_view()), name="eliminaruser"),
    url(r'^foro/administrador/$', login_required(ViewVistaAdministrador.as_view()), name="administradorr"),
    url(r'^foro/administrador/registrodeperfiles/$', login_required(ViewRegistroPerfilesUser.as_view()), name="registrodeperfile"),

    url(r'^Bienvenido/$', login_required(ViewForoBienvenido.as_view()), name="Bienvenido"),

    url(r'^Temas_Discusion/(?P<pk>\d+)/$', login_required(ViewVerListaPost.as_view()), name="mostrarListadoPost"),

    url(r'^perfil/', login_required(ViewVerPerfil.as_view()), name="perfil"),

    url(r'^registrotopico/', login_required(ViewRegistroTopico.as_view()), name="registro"),
    url(r'^Editar/', login_required(ViewListarTopicos.as_view()), name="Editar"),

    url(r'^ingresartemas/(?P<pk>\d+)$', login_required(ViewRegistroTemaEnPost.as_view()), name="ingresartemas"),

    url(r'^actualizarCategoria/$', login_required(ViewEditarCategoriaTopico.as_view()), name="actualizarCategoria"),
    url(r'^eliminarCategoria/$', login_required(ViewEliminarCategoriaTopico.as_view()), name="eliminarCategoria"),
    url(r'^agregarcategoria/$', login_required(ViewRegistroCategoriaTopico.as_view()), name="agregarcategoria"),

    url(r'^post/(?P<pk>\d+)$', login_required(ViewTemasDiscusion.as_view()), name="temadiscusion"),
    url(r'^editarcomentario/(?P<pk>\d+)$', login_required(ViewModificaComentario.as_view()), name="editarcomentario"),
    url(r'^eliminarcomentario/(?P<comentario>\d+)$', login_required(ViewEliminarComentario.as_view()), name="eliminarcomentario"),

    url(r'^actualizar/$', login_required(ViewEditarTopico.as_view()), name="actualizar"),
    url(r'^eliminar/$', login_required(ViewEliminarTopico.as_view()), name="eliminar"),

    url(r'^eliminar_post/(?P<post>\d+)$', login_required(ViewEliminarPost.as_view()), name="eliminarpost"),
    url(r'^Temas_Discusion/comentario/editarpost/(?P<post>\d+)$', login_required(ViewModificaPost.as_view()), name="editarpost"),

    url(r'^registrolike/', login_required(ViewRegistrarLike.as_view()), name="registrolike"),
    url(r'^eliminarlike/', login_required(ViewEliminarLike.as_view()), name="eliminarlike"),

    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),









    url(r'^foro/createuser/registrouser/$', login_required(ViewRegistroUser.as_view()), name="registrouser"),


    url(r'^foro/administrador/editarperfiles/(?P<pk>\d+)/$', login_required(ViewModificarPerfilesUser.as_view()), name="editarperfiles"),

    url(r'^foro/perfil/modificaruser/(?P<pk>\d+)/$', login_required(ViewModificarMiUser.as_view()), name="modificardatosuser"),
    url(r'^foro/perfil/modificardatosuser/(?P<username>[\w.@+-]+)/$', login_required(ViewModificarUser.as_view()), name="modificadouser"),

    url(r'^foro/perfil/eliminarperfile/(?P<pk>\d+)/$', login_required(ViewEliminarPerfilUser.as_view()), name="eliminarperfiles"),

    url(r'^', include('notifications.urls', namespace='notifications')),
    url(r'^foro/bienvenido/notificacionesredirrecionamiento/(?P<id>\d+)/(?P<informacion>[\w ]+)/(?P<pk>\d+)//$', login_required(ViewRedireccionNotificacions.as_view()), name="Notificacionesredirrecionamiento"),
    url(r'^foro/Bienvenido/Visualizarnotificaciones/$', ViewVisualizarNotificaciones.as_view(), name="visualizarnotificaciones"),




]

GeoDocs/GeoDocs/main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.views import logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.contrib.auth import views as v
from django.conf.urls import handler404,handler500

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'foro/', include('foro.urls')),
    path(r'repositorio/', include('repositorio.urls')),
    path(r'conversor/', include('conversor.urls')),
    path(r'mapa/', include('carto.urls')),
    url(r'^reset/password_reset', password_reset, {'template_name':'registration/password_reset_form.html','email_template_name': 'registration/password_reset_email.html'},name='password_reset'),
    url(r'^password_reset_done', password_reset_done,{'template_name': 'registration/password_reset_done.html'},name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,{'template_name': 'registration/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},name='password_reset_complete'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
handler404 = 'foro.views.error_404_view'
handler500 = 'foro.views.error_500'

GeoDocs/GeoDocs/repositorio/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.decorators import login_required

app_name='repositorio'



urlpatterns = [
        url(r'^$', login_required(ViewRepositorio.as_view()), name="Repositorio"),
        url(r'^repositorio/Visualizararchivos/tesis/Visualizararchivospdf/(?P<pk>\d+)$', login_required(ViewVisualizarTesisParaPDF.as_view()), name="Visualizararchivospdf"),
        url(r'^repositorio/Visualizararchivos/tesis/visualizarcategoriasdetesispaneladmin$', login_required(ViewVisualizarCategoriasTesisPaneladmin.as_view()), name="visualizarcategoriasdetesispaneladmin"),
        url(r'^repositorio/Visualizararchivos/tesis/(?P<pk>\d+)$', login_required(ViewVisualizarUnaTesis.as_view()), name="Visualizartesis"),
        url(r'^repositorio/GuardarArchivos/$', login_required(ViewGuardarTesis.as_view()), name="GuardarArchivos"),
        url(r'^repositorio/Visualizararchivos/tesis/filtro$', login_required(ViewFiltroDeTesisFecha.as_view()), name="filtro"),
        url(r'^repositorio/Visualizararchivos/tesis/filtroautor$', login_required(ViewFiltroDeTesisAutor.as_view()), name="filtroautor"),
        url(r'^repositorio/Visualizararchivos/tesis/filtronombre$', login_required(ViewFiltroDeTesisNombre.as_view()), name="filtronombre"),
        url(r'^repositorio/Visualizararchivos/tesis/buscadortotal$', login_required(ViewBuscarporPost.as_view()), name="buscadortota"),
        url(r'^repositorio/Visualizararchivos/tesis/modificaciontesis/(?P<pk>\d+)$', login_required(ViewModificarTesis.as_view()), name="modificaciontesi"),
        url(r'^repositorio/Visualizararchivos/tesis/eliminartesis/(?P<pk>\d+)$', login_required(ViewEliminarTesis.as_view()), name="eliminartesi"),
        url(r'^repositorio/registrocategoriastesis/$',  login_required(ViewRegistroCategoriaTesis.as_view()), name="registrocategoriastesis"),
        url(r'^repositorio/eliminartipotesis/(?P<pk>\d+)$', login_required(ViewEliminarTipoTesis.as_view()), name="eliminartipotesis"),
        url(r'^repositorio/modificarcategoriastesis/(?P<pk>\d+)$', login_required(ViewModificarCategoriaTesis.as_view()), name="modificarcategoriastesis"),
]

GeoDocs/GeoDocs/foro/models.py
from django.db import models
from cuentas.models import User
from django.contrib import admin
from datetime import datetime
from django.utils.html import mark_safe
from markdown import markdown
from django.db.models.signals import post_save
from notifications.signals import notify
#from topicos.models import Topicos


class Topico(models.Model):
    nombre = models.CharField(max_length=100,unique=True,blank=False)
    def __str__(self):
        return (self.nombre)

class Categoria(models.Model):
    nombre = models.CharField( max_length=50,unique=True,blank=False)
    topico = models.ForeignKey(Topico, on_delete=models.CASCADE)
    def __str__(self):
        return (self.nombre)

class Post(models.Model):
    titulo = models.CharField(max_length=50,unique=True,blank=False)
    descripcion = models.CharField(max_length=1000,blank=False)
    fecha = models.DateField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    user = models.ForeignKey(User,  on_delete=models.CASCADE)
    def __str__(self):
        return (self.titulo)

class Visitas(models.Model):
    visita = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User,  on_delete=models.CASCADE)


class Comentario(models.Model):
    comentario = models.CharField("Comentario", max_length=1000,blank=False)
    fecha = models.DateField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User,  on_delete=models.CASCADE)
    def __str__(self):
        return (self.comentario)
    def get_message_as_markdown(self):
            return mark_safe(markdown(self.comentario, safe_mode='escape'))


class Like(models.Model):
    comentario = models.ForeignKey(Comentario, on_delete=models.CASCADE)
    user = models.ForeignKey(User,  on_delete=models.CASCADE)

GeoDocs/GeoDocs/foro/templates/foro/administrador.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <title>Temas de Discusion</title>
    <meta charset="utf-8">
      <link rel="shortcut icon" href="{% static 'img\tituloimg.png'  %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'css/global.css'  %}"/>
  </head>
  <style media="screen">
          #contendor1{
            width: auto;
          }
          .sidenav {
          padding-top: 20px;
          background-color: #f1f1f1;
          height: 100%;
        }
        .navbar {
          margin-bottom: 0;
          border-radius: 0;
        }
        /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
      .row.content {height: 1500px}

      /* Set gray background color and 100% height */
      .sidenav {
        background-color: #f1f1f1;
        height: -webkit-fill-available;
      }

      /* Set black background color, white text and some padding */
      footer {
        background-color: #555;
        color: white;
        padding: 15px;
      }

      /* On small screens, set height to 'auto' for sidenav and grid */
      @media screen and (max-width: 767px) {
        .sidenav {
          height: 200px;
          padding: 15px;
        }
        .row.content {height: auto;}
      }
            .contenedor2 {
          position: relative;
          font-family: Arial;
      }

      .text-block {
          position: absolute;
          bottom: 20px;
          right: 20px;
          background-color: black;
          color: white;
          padding-left: 20px;
          padding-right: 20px;
      }
      .nav>li>a {
          position: relative;
          display: block;
          padding: 8px 16px;
      }
  </style>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <img src="{% static 'img\logo.png'  %}"  >
        </div>
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="myNavbar" style="margin-top:5px;">
            <ul class="nav navbar-nav">
              <li ><a href="{% url 'foro:administradorr' %}">Panel de Administrador</a></li>
              <li><a href="{% url 'carto:Mapa' %}">Mapa Georeferencial</a></li>
              <li><a href="{% url 'foro:Bienvenido' %}">Ir Foro</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'foro:perfil' %}"><span class="glyphicon glyphicon-user"></span> {{ user.email }}</a></li>
              <li><a href="{% url 'foro:logout' %}"><span class="glyphicon">&#xe163;</span> Cerrar sesion </a></li>
            </ul>
          </div>

        </div>
      </div>
    </nav>
    <div class="container-fluid"  id="contendor1">

        <div class="col-sm-1">

        </div>

          <div class="col-sm-2 sidenav" style=" margin-top: 15px;margin-bottom: 30px;border-radius: 10px;" >
          <ul class="nav nav-pills nav-stacked">
            <li class="active"><a href="{% url 'foro:visualizaradministrador' %}">Visualizar Administrador</a></li>
            <li><a href="{% url 'foro:visualizaruser' %}">Visualizar Usuarios</a></li>
            <li><a href="{% url 'foro:visualizarperfils' %}">Visualizar perfiles</a></li>
            <li><a href="{% url 'repositorio:Repositorio' %}">Visualizar Tesis</a></li>
            <li><a href="{% url 'repositorio:visualizarcategoriasdetesispaneladmin' %}">Visualizar Categorias de tesis  </a></li>
          </ul>
        </div>
        <br>
        <div class="col-sm-9 ">

          <div class="col-sm-1">

          </div>
          <div class="col-sm-9 .col-center">
            <div class="contenedor2">
              <img src="{% static 'img\comunidad.jpg'  %}" alt="Nature" style="width:100%; height:250px;">
              <div class="text-block">
                <h4>Administrador </h4>
              </div>
            </div>
              <h4><span class="glyphicon glyphicon-user"></span> Opciones de creacion de perfil y usuarios  </h4>
              <hr>
              <div class="panel panel-primary">
                <div class="panel-heading"><span class="glyphicon">&#xe032;</span> Desea Crear un perfil </div>
                <div class="panel-body">Ir a la vista de registro de perfil: <a class="btn btn-primary writebtn"  href="{% url 'foro:registrodeperfile' %}">Ir a la vista</a></div>
              </div>
              <div class="panel panel-success">
               <div class="panel-heading"><span class="glyphicon glyphicon-user"></span> Desea registrar un Usuario</div>
               <div class="panel-body">Ir a la vista registro de Usuario: <a class="btn btn-success writebtn"  href="{% url 'foro:registrouser' %}">Ir a la vista</a></div>
             </div>
             <hr>
             <h4><span class="glyphicon glyphicon-file"></span> Opciones de creacion de Categoria y Tesis  </h4>
             <hr>
             <div class="panel panel-primary">
               <div class="panel-heading"><span class="glyphicon">&#xe032;</span> Desea crear un categoria </div>
               <div class="panel-body">Desea ir a la vista de registro de categoria: <a class="btn btn-primary writebtn"  href="{% url 'repositorio:registrocategoriastesis' %}">Ir a la vista</a></div>
             </div>
             <div class="panel panel-success">
              <div class="panel-heading"><span class="glyphicon glyphicon-file"></span> Desea guardar una tesis</div>
              <div class="panel-body">Desea ir a la vista registro de tesis: <a class="btn btn-success writebtn"  href="{% url 'repositorio:GuardarArchivos' %}">Ir a la vista</a></div>
            </div>
          </div>
          <div class="col-sm-2">

          </div>
        </div>

    </div>





    </body>
  <footer class="container-fluid text-left">

  </a>
      <br><br>
  <p>Sitio website <a href="http://www.inacap.cl/tportalvp/construccion/" data-toggle="tooltip" >http://www.inacap.cl/tportalvp/construccion/</a></p>
    © 2018 Copyright Text<br>
</footer>
</html>

GeoDocs/GeoDocs/foro/templates/foro/visualizarperfiles.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
  <head>
    <title>Temas de Discusion</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="shortcut icon" href="{% static 'img\tituloimg.png'  %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'css/global.css'  %}"/>
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
  </head>
  <style media="screen">
          #contendor1{
            height: 770px
          }
          .sidenav {
          padding-top: 20px;
          background-color: #f1f1f1;
            height: -webkit-fill-available;
        }
        .navbar {
          margin-bottom: 0;
          border-radius: 0;
        }
        /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
      .row.content {height: 1500px}

      /* Set gray background color and 100% height */
      .sidenav {
        background-color: #f1f1f1;
        height: 100%;
      }

      /* Set black background color, white text and some padding */
      footer {
        background-color: #555;
        color: white;
        padding: 15px;
      }

      /* On small screens, set height to 'auto' for sidenav and grid */
      @media screen and (max-width: 767px) {
        .sidenav {
          height: 200px;
          padding: 15px;
        }
        .row.content {height: auto;}
      }
      .nav>li>a {
          position: relative;
          display: block;
          padding: 8px 16px;
      }
  </style>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <img src="{% static 'img\logo.png'  %}"  >
        </div>
        <div class="container-fluid">
        <div class="collapse navbar-collapse" id="myNavbar" style="    margin-top: 10px;">
            <ul class="nav navbar-nav">
              <li ><a href="{% url 'foro:administradorr' %}">Panel de Administrador</a></li>
              <li><a href="{% url 'carto:Mapa' %}">Mapa Georeferencial</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'foro:perfil' %}"><span class="glyphicon glyphicon-user"></span> {{ user.email }}</a></li>
              <li><a href="{% url 'foro:logout' %}"><span class="glyphicon">&#xe163;</span> Cerrar sesion </a></li>
            </ul>
          </div>

        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row content" id="contendor1">
        <div class="col-sm-1">
        </div>
        <div class="col-sm-2 sidenav" style=" margin-top: 15px;margin-bottom: 30px;border-radius: 10px;" >
        <ul class="nav nav-pills nav-stacked" style="margin-top: -10px;">
          <li ><a href="{% url 'foro:visualizaradministrador' %}">Visualizar Administrador</a></li>
          <li ><a href="{% url 'foro:visualizaruser' %}">Visualizar Usuarios</a></li>
          <li class="active"><a href="{% url 'foro:visualizarperfils' %}">Visualizar perfiles</a></li>
          <li><a href="{% url 'repositorio:Repositorio' %}">Visualizar Tesis</a></li>
          <li><a href="{% url 'repositorio:visualizarcategoriasdetesispaneladmin' %}">Visualizar Categorias de tesis  </a></li>
        </ul>
      </div>
          <div class="col-sm-9 ">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-9 .col-center">
              <h2>Perfiles de Usuarios</h2>

              <hr>
              <h4><small>Informacion de los Usuarios creados </small></h4>
              {% if messages %}
              {% for message in messages %}
              <p{%if message.tags == "success"  %} class="alert alert-info" {%endif%}><strong>Info! </strong>{{message}}</p>
              {%endfor%}
            {%endif%}
              <div class="table">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th scope="col">Configuracion</th>
                      <th scope="col">Perfil</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for obj in object_list%}

                    {% if obj.id == 1 %}
                    <td  align="center">Administrador: <i style='font-size:24px' class='fas'>&#xf007;</i></td>
                    {%else %}
                    <tr>
                      <th class="dropdown">
                        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span><span class="caret"></span></button>
                        <ul class="dropdown-menu dropdown-menu-right">
                          <li><a href="{% url 'foro:eliminarperfiles' pk=obj.id  %}"><button type="button" class="btn btn-danger" style="width: 94px;"> Eliminar <span class="glyphicon glyphicon-trash"></span></button></a></li>
                          <li><a href="{% url 'foro:editarperfiles' pk=obj.id  %}"><button type="button" class="btn btn-success" style="width: 94px;">   Editar <span class="glyphicon glyphicon-edit"></span></button></a></li>
                        </ul>
                      </th>
                      {%endif%}


                      <td  align="center" >{{obj.perfil}}</td>
                    </tr>
                    {%endfor%}
                  </tbody>
                </table>
              </div>
            </div>
            <div class="col-sm-2">
            </div>
          </div>
        </div>
      </div>
    </body>
  <footer class="container-fluid text-left">

  </a>
      <br><br>
  <p>Sitio website <a href="http://www.inacap.cl/tportalvp/construccion/" data-toggle="tooltip" >http://www.inacap.cl/tportalvp/construccion/</a></p>
    © 2018 Copyright Text<br>
</footer>
</html>